package br.com.felipedevbino.arquivos;

//CLASSE RESPONSÁVEL POR FORNECER MÉTODOS QUE LIDAM COM SALVAMENTO DE DADOS GERAIS DO ORÇAMENTO
//COMO OS MAPAS, CONFIGURAÇÕES, E TUDO QUE O USUÁRIO POSSA PRECISAR EM FUTURAS OPERAÇÕES 
public class Orcamento {

}
