package br.com.felipedevbino.arquivos;

//CLASSE RESPONSÁVEL POR FORNECER MÉTODOS QUE TRABALHAM COM O SALVAMENTO DE POSIÇÕES
//NA TELA INTERATIVA, O SISTEMA DEVE PERGUNTAR AO USUÁRIO SE ELE DESEJA APLICAR AS
//POSIÇÕES ANTERIORES BASEADO NO ARQUIVO EM QUESTÃO.
public class PosicoesNoPainel {

}
